operations:
    offer_pause:
        label: 'Fill Resource'
        entities:
            - 'FM\Bundle\ResourceBundle\Entity\Resource'
        acl_resource: fm_resource_update
        routes:
            - fm_resource_index
            - fm_resource_view
        groups:
            - datagridRowAction
        button_options:
            icon: fa-play
            class: btn-danger icons-holder-text
        datagrids:
            - fm-resource-grid
        datagrid_options:
            mass_action:
                type: handle_resource
                label: 'Fill Data'
                icon: play
                handler: fm.datagrid.extension.mass_action.handler.handle_resource
                data_identifier: o.id
                object_identifier: o
                confirmation: true
                acl_resource: fm_resource_update
        actions:
            - '@run_action_group':
                action_group: fillData
                parameters_mapping:
                    data: $.data
action_groups:
    fillData:
        parameters:
            data:
                type: FM\ResourceBundle\Entity\Resource
        actions:
            - '@assign_value': [$.data.status, 'progress']
            - '@flush_entity': $.data
            - '@flash_message':
                message: 'Resource %%name%% were requested to fill data'
                type: 'success'
                message_parameters:
                    'name': $.data.name
