services:
    ### Project Form and Type
    fm.form.project:
        public: true
        class: Symfony\Component\Form\Form
        factory: ["@form.factory", createNamed]
        arguments: ["project_form", 'FM\Bundle\ProjectBundle\Form\Type\ProjectType', null]

    fm.form.type.project:
        class: FM\Bundle\ProjectBundle\Form\Type\ProjectType
        arguments:
            - 'FM\Bundle\ProjectBundle\Entity\Project'
        tags:
            - { name: form.type, alias: fm_project }
    fm.form.handler.project:
        class: FM\Bundle\ProjectBundle\Form\Handler\ProjectHandler
        # This service marked as public for compatibility with Symfony 4. All dependencies must be refactored after BAP-17037
        public: true
        arguments:
            - "@fm.form.project"
            - "@request_stack"
            - "@doctrine.orm.entity_manager"
