parameters:
    fm.importexport.processor.import.processor.class: FM\Bundle\ResourceBundle\ImportExport\Processor\AddOwnerProcessor
    fm.importexport.strategy.resource.add_bu.class: FM\Bundle\ResourceBundle\ImportExport\Strategy\AddOrReplaceStrategy

services:
    # import form type extension
    fm.importexport.resource.form_type_extension:
        class: FM\Bundle\ResourceBundle\Form\Extension\BUImportTypeExtension
        tags:
            - { name: form.type_extension, extended_type: oro_importexport_import, alias: oro_importexport_import }

    # Strategy
    fm.importexport.strategy.resource.add_or_replace:
        class: '%fm.importexport.strategy.resource.add_bu.class%'
        parent: oro_importexport.strategy.configurable_add_or_replace

    # Converter
    fm.importexport.data_converter.resource:
        parent: oro_importexport.data_converter.configurable
    fm.importexport.template_fixture.data_converter.resource:
        parent: oro_importexport.data_converter.template_fixture.configurable

    # Import processor
    fm.importexport.processor.import:
        parent: oro_importexport.processor.import_abstract
        class: '%fm.importexport.processor.import.processor.class%'
        calls:
            - [setDataConverter, ['@fm.importexport.data_converter.resource']]
            - [setStrategy, ['@fm.importexport.strategy.resource.add_or_replace']]
        tags:
            - { name: oro_importexport.processor, type: import, entity: '%fm.entity.resource.class%', alias: fm.resource.add_or_replace }
            - { name: oro_importexport.processor, type: import_validation, entity: '%fm.entity.resource.class%', alias: fm.resource.add_or_replace }

    # Export processor
    fm.importexport.processor.export:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, ['@fm.importexport.data_converter.resource']]
        tags:
            - { name: oro_importexport.processor, type: export, entity: '%fm.entity.resource.class%', alias: fm_resource }

    fm.importexport.processor.export_template:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, ['@fm.importexport.template_fixture.data_converter.resource']]
        tags:
            - { name: oro_importexport.processor, type: export_template, entity: '%fm.entity.resource.class%', alias: fm_resource }

    # Helper
    fm.importexport.configuration_provider.resource:
        class: 'FM\Bundle\ResourceBundle\ImportExport\Configuration\ResourceImportExportConfigurationProvider'
        tags:
            - { name: oro_importexport.configuration, alias: fm_resource }
