parameters:
    fm.resource.entity.class: FM\PlatformBundle\Entity\Resource
    fm.importexport.processor.import.bu_fill.class: FM\PlatformBundle\ImportExport\Processor\FillBuProcessor
    fm.importexport.strategy.resource.add_bu.class: FM\PlatformBundle\ImportExport\Strategy\AddBuStrategy

services:
    # import form type extension
    fm.importexport.resource.form_type_extension:
        class: FM\PlatformBundle\Form\Extension\BUImportTypeExtension
        tags:
            - { name: form.type_extension, extended_type: oro_importexport_import, alias: oro_importexport_import }

    # Strategy
    fm.importexport.strategy.resource.add_or_replace:
        class: '%fm.importexport.strategy.resource.add_bu.class%'
        parent: oro_importexport.strategy.configurable_add_or_replace

    # Converter
    fm.importexport.data_converter.resource:
        parent: oro_importexport.data_converter.configurable
    fm.importexport.template_fixture.data_converter.resource:
        parent: oro_importexport.data_converter.template_fixture.configurable

    # Import processor
    fm.importexport.processor.import.add_or_replace:
        parent: oro_importexport.processor.import_abstract
        class: '%fm.importexport.processor.import.bu_fill.class%'
        calls:
            - [setDataConverter, ['@fm.importexport.data_converter.resource']]
            - [setStrategy, ['@fm.importexport.strategy.resource.add_or_replace']]
        tags:
            - { name: oro_importexport.processor, type: import, entity: '%fm.resource.entity.class%', alias: fm.resource.add_or_replace }
            - { name: oro_importexport.processor, type: import_validation, entity: '%fm.resource.entity.class%', alias: fm.resource.add_or_replace }

    # Export processor
    fm.importexport.processor.export:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, ['@fm.importexport.data_converter.resource']]
        tags:
            - { name: oro_importexport.processor, type: export, entity: '%fm.resource.entity.class%', alias: fm.resource }

    fm.importexport.processor.export_template:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, ['@fm.importexport.template_fixture.data_converter.resource']]
        tags:
            - { name: oro_importexport.processor, type: export_template, entity: '%fm.resource.entity.class%', alias: fm.resource }

    # Helper
    fm.importexport.configuration_provider.contact:
        class: 'FM\PlatformBundle\ImportExport\Configuration\ResourceImportExportConfigurationProvider'
        arguments:
            - '@translator'
        tags:
            - { name: oro_importexport.configuration, alias: fm.resource }
