imports:
    - { resource: mass_actions.yml }

services:
    fm.api.manager:
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - '%fm.resource.entity.class%'
            - '@doctrine.orm.entity_manager'

#    fm.listener.navigation_listener:
#        class: 'FM\PlatformBundle\EventListener\NavigationListener'
#        arguments:
#            - '@oro_entity.doctrine_helper'
#            - '@oro_entity_config.provider.entity'
#            - '@oro_security.token_accessor'
#            - '@oro_security.acl_helper'
#        tags:
#            - { name: kernel.event_listener, event: oro_menu.configure.application_menu, method: onNavigationConfigure }
