navigation:
    menu_config:
        items:
            fm_project_tab:
                label: fm.nav.project.label
                uri:   '#'
                extras:
                    position: 10
            fm_contract_tab:
                label: fm.nav.contract.label
                uri:   '#'
                extras:
                    position: 20
            fm_resource_tab:
                label: fm.nav.resource.label
                uri:   '#'
                extras:
                    position: 30
            resource_link:
                label: fm.nav.resource.plural_label
                route: fm_resource_index
            contract_link:
                label: fm.nav.contract.plural_label
                route: fm_contract_index
            project_link:
                label: fm.nav.project.plural_label
                route: fm_project_index
            channel_link:
                label: fm.nav.channel.plural_label
                route: fm_channel_index
            platform_link:
                label: fm.nav.platform.plural_label
                route: fm_platform_index
        tree:
            application_menu:
                children:
                    fm_project_tab:
                        children:
                            project_link: ~
                    fm_contract_tab:
                        children:
                            contract_link: ~
                    fm_resource_tab:
                        children:
                            resource_link: ~
                            channel_link: ~
                            platform_link: ~

    titles:
        contract_link: fm.nav.contract.plural_label
        resource_link: 'KOL Lists'
        project_link: fm.nav.project.plural_label
        platform_link: fm.nav.platform.plural_label
        channel_link: fm.nav.channel.plural_label
