datagrids:
    fm-channel-grid:
        extended_entity_name: '%fm.entity.channel.class%'
        acl_resource: fm_resource_view
        inline_editing:
            enable: true
        source:
            type: orm
            query:
                select:
                    - c
                from:
                    - { table: '%fm.entity.channel.class%', alias: c }
        columns:
            id:
                label:         oro.channel.id.label
            name:
                label:         fm.entity.name.label
            person:
                label:         fm.datagrid.channel.person
                type:          twig
                frontend_type: html
                template:      FMResourceBundle::Datagrid/Property/person.html.twig
            createdAt:
                label:         oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label:         oro.ui.updated_at
                frontend_type: datetime
        sorters:
            columns:
                name:
                    data_name: c.name
                createdAt:
                    data_name: c.createdAt
            default:
                createdAt: DESC
        filters:
            columns:
                name:
                    type: string
                    data_name: c.name
                person:
                    type: single_choice
                    data_name: c.person
                    options:
                        field_options:
                            choices:
                                1: 'Yes'
                                0: 'No'
                createdAt:
                    type: date
                    data_name: k.createdAt
        options:
            export: true
            entity_pagination: true
